name: Release

on:
  push:
    tags:
      - '*.*.*'
      
jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: "conda-incubator/setup-miniconda@v2"
      with:
        activate-environment: phold_env
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
        miniforge-variant: Mambaforge
        channels: conda-forge,bioconda,defaults
        channel-priority: strict
        auto-update-conda: true
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package to Pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}


